name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build-artifact:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      # TEST STAGE
      - name: Compile Test (Syntax Validation)
        run: |
          python -m py_compile api_collector.py
          python -m py_compile monitor.py

      # BUILD DATA (generate logs)
      - name: Generate API Logs
        run: |
          python api_collector.py

      # ARTIFACT
      - name: Upload Logs Artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-logs
          path: logs/